# ===============================
# PRODUCCION - Overrides
# ===============================

# Evita validacion de schema al iniciar (reduce startup ~30s) 
spring.jpa.hibernate.ddl-auto=validate

# Dialecto MySQL explícito (necesario cuando ddl-auto=validate)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
