# ===============================
# PRODUCCION - Overrides
# ===============================

# Evita validacion de schema al iniciar (reduce startup ~30s)
spring.jpa.hibernate.ddl-auto=validate

# Evita consulta de metadatos JDBC al iniciar (reduce startup ~20s)
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
